name: Weekly Zillow Report

on:
  schedule:
    - cron: '30 13 * * 2'  # Every Tuesday at 9:30 AM ET (13:30 UTC)
  workflow_dispatch:        # Allows manual triggering
  push:                     # Also runs when you push to main
    branches:
      - main

jobs:
  run-report:
    runs-on: ubuntu-latest
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dependencies
        run: pip install --upgrade webdriver_manager
      - name: Run main.py
        run: python main.py
