name: Weekly Zillow Report

on:
  schedule:
    - cron: '30 13 * * 2'   # Tue 09:30 AM ET
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-report:
    runs-on: ubuntu-latest
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install -r requirements.txt
      - name: Run main.py
        run: python main.py
